version: 0.2

phases:
    install:
        commands:
            - ./dotnet-install.ps1 --channel LTS
            
    build:
        commands:
            - dotnet build -c Release ./BlazorOnAWS.csproj
            - dotnet publish -o deployfolder
            
artifacts:
    files:
        - deployfolder/*.*
        - aws-windows-deployment-manifest.json
