version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 6.0
    build:
        commands:
            - dotnet build -c Release ./BlazorOnAWS.csproj
            - dotnet publish -o deployfolder
            
artifacts:
    files:
        - deployfolder/*.*
        - aws-windows-deployment-manifest.json
