version: 0.2

phases:
    install:
        commands:
            - pwsh
            - pwsh -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1'"
            - pwsh -Command "./dotnet-install.ps1 -Channel 6.0.2"
            
    build:
        commands:
            - dotnet build -c Release ./BlazorOnAWS.csproj
            - dotnet publish -o deployfolder
            
artifacts:
    files:
        - deployfolder/*.*
        - aws-windows-deployment-manifest.json
