version: 0.2

phases:
    install:
        commands:
            - powershell -command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -Proxy $env:HTTP_PROXY -ProxyUseDefaultCredentials -OutFile 'dotnet-install.ps1'"
            - powershell -command "./dotnet-install.ps1 -Channel LTS"
            
    build:
        commands:
            - dotnet build -c Release ./BlazorOnAWS.csproj
            - dotnet publish -o deployfolder
            
artifacts:
    files:
        - deployfolder/*.*
        - aws-windows-deployment-manifest.json
